
ez:
    path: /webcomponents/ez-yui-app.html
    defaults:
        _controller: ezsystems.platformui.controller:yuiAppAction

template_yui_module:
    path: /tpl/handlebars/{module}.js
    defaults:
        _controller: ezsystems.platformui.controller.template:wrapTemplateAction
        _format: js
    methods: [GET]

ez_pjax:
    resource: "@eZPlatformUIBundle/Resources/config/routing_pjax.yml"
    prefix:   /pjax

yui_combo_loader:
    path: /_ezcombo
    defaults:
        _controller: ezsystems.platformui.controller:combineLoaderAction

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
